/*
  PROJECT CONTENT FILE
  --------------------
  Add or edit your project information here. This site intentionally uses
  placeholders so every project description can be written in your own voice.
*/
window.portfolioProjects = [
  {
    slug: "cookstove",
    title: "Clean Cookstove",
    organization: "Burn Design Lab",
    date: "Jan 2026 - June 2026",
    category: "Sustainable Product Design",
    visual: "cookstove",
    image: "",
    imageCaption: "Add a caption describing the project image.",
    statCitation: { label: "Cookstove Project", url: "https://cookstoveproject.org" },
    problemLead: "2.1 billion people cook over open fires (cookstoveproject.org).",
    problem: "Cooking over open fires is a major source of indoor air pollution, promoting respiratory illness and contributing to climate change.",
    roleLead: "Mechanical Design Intern",
    role: "I co-designed, fabricated, and tested four sheet metal cookstove models for Senegal and Sierra Leone.",
    skillsUsed: ["Human centered design", "Sheet metal design", "Fabrication", "Test sequence design", "Fusion 360","Donor communication"],
    solutionLead: "Sheet metal cookstoves that increase thermal efficiency up to 4x and reduce harmful pollutants.",
    solution: "All components are designed for local fabrication and assembly with minimal tooling and energy access. These stoves will be sold at an accessible price of approximately $30.",
    cardDescription: "Affordable and efficient cookstove development for developing nations.",
  },
  {
    slug: "orpc-buoy-release",
    title: "Buoy Release System",
    organization: "Ocean Renewable Power Company × UW Capstone",
    date: "June 2026",
    category: "Energy Systems",
    visual: "buoy",
    image: "assets/images/RivGenPrimaryPic.jpg",
    images: [
      { src: "assets/images/RivGenPrimaryPic.jpg", caption: "ORPC's RivGen turbine in Igiugig, Alaska." }
    ],
    imageCaption: "ORPC's RivGen turbine in Igiugig, Alaska.",
    mediaLayout: "image",
    problemLead: "A lower-cost release system for an Alaskan river turbine",
    problem: "For the UW Senior Capstone, our team developed a pop-up buoy release for a hydrokinetic river turbine operating in Alaska. The system needed to respond to river conditions while remaining simpler and less expensive than the existing release approach.",
    roleLead: "Client liaison and testing lead",
    role: "I coordinated with ORPC engineers, translated project requirements into testable failure modes, and led the flow and sediment testing plan.",
    skillsUsed: ["Test planning", "Failure-mode analysis", "Client communication", "Flow testing"],
    solutionLead: "10/10 actuations at 1 m/s river conditions",
    solution: "The servo-actuated buoy mechanism eliminated a $25,000-plus acoustic release system and brought the total assembly cost below $5,000.",
    cardDescription: "A lower-cost release system for an Alaskan river turbine",
  },
  {
    slug: "submarine-propeller",
    title: "Human-Powered Submarine Propeller",
    organization: "University of Washington",
    date: "June 2024",
    category: "Computational Design",
    visual: "propeller",
    image: "",
    imageCaption: "Add a caption describing the project image.",
    model: "assets/models/B1%20High%20Acceleration.glb",
    modelCaption: "High-Acceleration Propeller optimized for a large diameter.",
    images: [
      { src: "assets/images/BladePrimary.png", caption: "Manufactured propeller profile, using a shortened diameter for manufacturability.", alt: "Manufactured propeller profile, using a shortened diameter for manufacturability." },
      { src: "assets/images/BladeGraph.png", caption: "Propeller functionality over advance ratio: green line shows power efficiency and dashed line shows target RPM at 4 m/s.", alt: "Propeller Functionality Over Advance Ratio (Green Line: Power Efficiency, Dashed Line: Target RPM (4 m/s))" }
    ],
    mediaLayout: "image",
    cardDescription: "A lower-cost release system for an Alaskan river turbine",
    problemLead: "Propeller profile design for a human-powered submarine.",
    problem: "Human submarines require very unique propeller characteristics with incredibly low thrust and rpm relative to industrial counterparts. As such, a custom profile is required to maximize efficiency and performance.",
    roleLead: "Mechanical engineering project contributor",
    role: "I supported the design process by translating performance goals into a geometry that could be analyzed, refined, and fabricated.",
    skillsUsed: ["Computational design", "CAD modeling", "Performance analysis", "Design iteration"],
    solutionLead: "A computationally optimized propeller design.",
    solution: "Using the open-source propeller design package OpenProp, I iterated through various propeller geometries to optimize for the target parameters and acceleration profile for the relevant event needs. The final design was fabricated in carbon fiber and used in the 2025 International Submarine Races.",
  },
  {
    slug: "cryo-perfusion",
    title: "Organ Perfusion System",
    organization: "Center for Cryo-Biomedical Engineering and Artificial Organs",
    date: "Sep 2025 - Jan 2026",
    category: "Medical Device Prototyping",
    visual: "perfusion",
    image: "",
    model: "assets/models/Organ%20Rack%20V1.1.glb",
    modelCaption: "A removable rack for the mobile perfusion of a human kidney with cryoprotective agents.",
    imageCaption: "Add a caption describing the project image.",
    images: [
      { src: "assets/images/OrganPrimary.png", caption: "Prototype assembly of mobile perfusion system.", alt: "Human kidney perfusion system prototype. The kidney would be placed in the rack and intubated for perfusion." },
      { src: "assets/images/OrganDia.png", caption: "Organ perfusion system diagram.", alt: "Organ perfusion system diagram" }
    ],
    statCitation: { label: "Warren Cornwall, \"Frozen in Time,\" Science, 21 June 2023", url: "https://doi.org/10.1126/science.adj3555" },
    problemLead: "Only 10% of organ failure patients receive the transplant they need (Science).",
    problem: "Organ donations are often rejected due to transportation delays, leading to a severe supply constraint for those in need. How do we extend the period of organ viability?",
    roleLead: "Engineering Research assistant",
    role: "I adapted and enclosed the benchtop research setup for a hospital environment, optimizing for manufacturability, inuitive use, and biocompatibility.",
    skillsUsed: ["Medical device prototyping", "Design for manufacturing", "CAD modeling", "Prototype iteration"],
    solutionLead: "Perfuse the organ with cryoprotective agents and freeze it for transport",
    solution: "The system is designed to perfuse a human kidney with cryoprotective agents that permit the kidney to be frozen with minimal cell damage. The organ can then be transported and thawed for transport. The perfusion system is designed to be mobile, allowing for organ perfusion in a variety of locations.",
    cardDescription: "Developing systems to permit the cryogenic preservation of donor organs.",
  },
  {
    slug: "electroimpact-jigs",
    title: "Production Support Jigs",
    organization: "Electroimpact",
    date: "June 2025",
    category: "Design for Manufacturing",
    visual: "jigs",
    image: "",
    imageCaption: "Add a caption describing the project image.",
    images: [
      { src: "assets/images/Toe Feed Jig.png", caption: "FEP plastic trimming assembly jig (blades not shown).", alt: "Toe feed production support jig" },
      { src: "assets/images/Roller Jig.png", caption: "Press fit orientation jig for machined part.", alt: "Roller production support jig" }
    ],
    mediaLayout: "image",
    problemLead: "High scrap rates and production delays in a high-volume aerospace manufacturing environment.",
    problem: "Electroimapact's automated fiber placement machines require precise assembly of spare parts. The red rollers shown in the image above required the plastic to be trimmed with a tolerance below a half milimeter, by hand! This understandably led to high scrap rates and production delays due to human error.",
    roleLead: "Intern",
    role: "I was responsible for spare part assembly within the automated fiber placement department.",
    skillsUsed: ["SolidWorks", "Jig Design", "Component Sourcing", "Production support"],
    solutionLead: "Assembly aids for manufacturing productivity",
    solution: "I utilized SolidWorks to design and iterate production support jigs for assembly, focusing on manufacturability and ease of use in a high-precision production environment.",
    cardDescription: "Assemblies aiding in the high-precision assembly of aerospace manufacturing systems.",
  },
  {
    slug: "candy-bowl",
    title: "Challenge-Activated Candy Dispenser",
    organization: "UW Intro to Capstone",
    date: "Sep 2025 - Dec 2025",
    category: "Rapid Fabrication",
    visual: "candy",
    images: [
      { src: "assets/images/CandyHero.png", caption: "An overview of the candy dispenser.", alt: "Candy dispenser overview" },
      { src: "assets/images/CandyOver.png", caption: "A diagram of intended use.", alt: "Candy dispenser intended use" }
    ],
    model: "assets/models/pinball.glb",
    modelCaption: "This is a pinball style puzzle. The user loads and fires a chocolate candy from the launcher and manipulates the obstacles to avoid the holes, successfully dispenseing the candy.",
    modelOrientation: "180deg 180deg 0deg",
    problemLead: "University faculty need creative ways to encourage student engagment.",
    problem: "How do we encourage students to feel comfortable, engaged, and entertained in faculty offices?",
    roleLead: "Fabrication and Assembly",
    role: "I lead fabrication and assembly of the candy dispenser, including laser cutting, 3D printing, and mechanical assembly.",
    skillsUsed: ["SolidWorks", "3D Printing/Laser Fabrication", "Human Centered Design", "Rapid prototyping"],
    solutionLead: "A challenge-activated candy dispenser.",
    solution: "The pinball style puzzle requires the user to load and fire a chocolate candy from the launcher, then manipulate the obstacles to avoid the holes and successfully dispense the candy. The dispenser is designed to be engaging and entertaining enough to encourage student interaction with faculty.",
    cardDescription: "A challenge-activated candy dispenser for a capstone course.",
  }
];
