/*
  PROJECT CONTENT FILE
  --------------------
  Add or edit your project information here. This site intentionally uses
  placeholders so every project description can be written in your own voice.
*/
window.portfolioProjects = [
  {
    slug: "cookstove",
    title: "Clean Cookstove",
    client: "Burn Design Lab",
    date: "2026",
    category: "Sustainable Product Design",
    visual: "cookstove",
    image: "",
    imageCaption: "Add a caption describing the project image.",
    overviewLead: "2.1 billion people cook over open fires (cookstoveproject.org).",
    overview: "My work with the Burn Design Lab focused on designing a clean cookstove that reduces emissions and improves efficiency for low-income households in developing nations.",
    roleLead: "Mechanical Design Intern",
    role: "I co-designed, fabricated, and tested four sheet metal cookstove models for Senegal and Sierra Leone.",
    skills: ["Sheet metal design", "Fabrication", "Thermal testing", "Fusion 360"],
    outcomesLead: "Above 40% thermal efficiency",
    outcomes: "The cookstoves will be produced at an estimated $30 unit price.",
  },
  {
    slug: "orpc-buoy-release",
    title: "Buoy Release System",
    client: "Ocean Renewable Power Company × UW Capstone",
    date: "2026",
    category: "Energy Systems",
    visual: "buoy",
    image: "assets/images/RivGenPrimaryPic.jpg",
    images: [
      { src: "assets/images/RivGenPrimaryPic.jpg", caption: "ORPC's RivGen turbine in Igiugig, Alaska." }
    ],
    imageCaption: "ORPC's RivGen turbine in Igiugig, Alaska.",
    mediaLayout: "image",
    overviewLead: "A lower-cost release system for an Alaskan river turbine",
    overview: "For the UW Senior Capstone, our team developed a pop-up buoy release for a hydrokinetic river turbine operating in Alaska. The system needed to respond to river conditions while remaining simpler and less expensive than the existing release approach.",
    roleLead: "Client liaison and testing lead",
    role: "I coordinated with ORPC engineers, translated project requirements into testable failure modes, and led the flow and sediment testing plan.",
    skills: ["Test planning", "Failure-mode analysis", "Client communication", "Flow testing"],
    outcomesLead: "10/10 actuations at 1 m/s river conditions",
    outcomes: "The servo-actuated buoy mechanism eliminated a $25,000-plus acoustic release system and brought the total assembly cost below $5,000.",
  },
  {
    slug: "submarine-propeller",
    title: "Human-Powered Submarine Propeller",
    client: "University of Washington",
    date: "2024",
    category: "Computational Design",
    visual: "propeller",
    image: "",
    imageCaption: "Add a caption describing the project image.",
    model: "assets/models/B1%20High%20Acceleration.glb",
    modelLabel: "High-Acceleration Propeller",
    images: [
      { src: "assets/images/BladePrimary.png", caption: "Primary propeller blade geometry.", alt: "Propeller blade geometry" },
      { src: "assets/images/BladeGraph.png", caption: "Blade performance graph used during the design process.", alt: "Propeller blade performance graph" }
    ],
    mediaLayout: "image",
    overviewLead: "Computational design for a human-powered submarine",
    overview: "The propeller project explored computational design for a human-powered submarine at the University of Washington. The work focused on connecting performance requirements with a practical, manufacturable propeller geometry.",
    roleLead: "Mechanical engineering project contributor",
    role: "I supported the design process by translating performance goals into a geometry that could be analyzed, refined, and fabricated.",
    skills: ["Computational design", "CAD modeling", "Performance analysis", "Design iteration"],
    outcomesLead: "",
    outcomes: "Add the final performance result, comparison, or competition outcome here.",
  },
  {
    slug: "cryo-perfusion",
    title: "Organ Perfusion System",
    client: "Center for Cryo-Biomedical Engineering and Artificial Organs",
    date: "Sep 2025 - Jan 2026",
    category: "Medical Device Prototyping",
    visual: "perfusion",
    image: "",
    model: "assets/models/Organ%20Rack%20V1.1.glb",
    modelLabel: "Interactive CAD model of a human kidney rack.",
    imageCaption: "Add a caption describing the project image.",
    overviewLead: "Prototype hardware for donor-kidney perfusion research",
    overview: "The Gao Lab project focused on prototype hardware for an organ perfusion system supporting the vitrification of donor kidneys. The work combined medical-device constraints with the practical demands of a system moving toward formal testing.",
    roleLead: "Research assistant",
    role: "At the Center for Cryo-Biomedical Engineering and Artificial Organs, I developed and iterated prototype hardware and refined the design for manufacturability.",
    skills: ["Medical device prototyping", "Design for manufacturing", "CAD modeling", "Prototype iteration"],
    outcomesLead: "Updated organ-rack prototype",
    outcomes: "Delivered an updated organ-rack prototype and design refinements ahead of the formal testing phase.",
  },
  {
    slug: "electroimpact-jigs",
    title: "Production Support Jigs",
    client: "Electroimpact",
    date: "2025",
    category: "Design for Manufacturing",
    visual: "jigs",
    image: "",
    imageCaption: "Add a caption describing the project image.",
    mediaLayout: "image",
    overviewLead: "Production support for more than 100 spare-part projects",
    overview: "At Electroimpact, I supported a high-volume spare-parts operation while designing practical assembly aids for manufacturing teams.",
    roleLead: "Engineering intern",
    role: "I co-managed component sourcing, assembly, and invoicing for more than 100 simultaneous spare-part projects and designed production support tooling in SolidWorks.",
    skills: ["SolidWorks", "Jig design", "Component sourcing", "Production support"],
    outcomesLead: "Assembly aids for manufacturing productivity",
    outcomes: "Created assembly aids intended to increase manufacturing productivity while supporting a large, active portfolio of spare-part projects.",
  },
  {
    slug: "vr-lens",
    title: "VR Lens Adjustment",
    client: "Witwerx Engineering",
    date: "2021",
    category: "Mechanism Design",
    visual: "lens",
    image: "",
    imageCaption: "Add a caption describing the project image.",
    overviewLead: "",
    overview: "Write a concise overview of the problem, your contribution, and why this work mattered.",
    roleLead: "",
    role: "Add your responsibilities, collaborators, and the project context.",
    skills: ["Mechanism design", "CAD modeling", "Prototype development"],
    outcomesLead: "",
    outcomes: "Add measurable outcomes, results, lessons, or next steps.",
  },
  {
    slug: "candy-bowl",
    title: "Challenge-Activated Candy Dispenser",
    client: "UW Intro to Capstone",
    date: "Sep 2025 - Dec 2025",
    category: "Rapid Fabrication",
    visual: "candy",
    images: [
      { src: "assets/images/CandyHero.png", caption: "An overview of the candy dispenser.", alt: "Candy dispenser overview" },
      { src: "assets/images/CandyOver.png", caption: "A diagram of intended use.", alt: "Candy dispenser intended use" }
    ],
    model: "assets/models/pinball.glb",
    modelLabel: "This is a pinball style puzzle. The user loads and fires a chocolate candy from the launcher, thenmanipulates the obstacles to avoid the holes and successfully dispense the candy.",
    modelOrientation: "180deg 180deg 0deg",
    overviewLead: "A challenge-activated candy dispenser for a capstone course.",
    overview: "A high-speed design and fabrication project, focused on meeting client expectations with an eight week timeline with creative and competitive solutions.",
    roleLead: "Fabrication and Assembly",
    role: "I lead fabrication and assembly of the candy dispenser, including laser cutting, 3D printing, and mechanical assembly.",
    skills: ["SolidWorks", "3D Printing/Laser Fabrication", "Human Centered Design", "Rapid prototyping"],
    outcomesLead: "",
    outcomes: "Add measurable outcomes, results, lessons, or next steps.",
  }
];
